name: CI linux

on:
  push:
    paths-ignore:
      - 'doc/**'

  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:

  build:
    name: CI on ${{ matrix.tag }}
 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        tag: # Those are our dockerhub alire/gnat:tag machines
            - community-current
            - debian-stable
            - ubuntu-lts
 
    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Check out submodules
      run: git submodule update --init --recursive

    - name: Pull docker image
      run: docker pull alire/gnat:${{ matrix.tag }}

    - name: Build & test
      run: docker run -v${PWD}:/ci -w /ci -e "BRANCH=${{ github.base_ref }}" alire/gnat:${{ matrix.tag }} scripts/ci-github.sh
